# Generated by Django 3.0.8 on 2022-04-03 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviews', models.TextField(verbose_name=' Reviews ')),
                ('name', models.CharField(max_length=50, verbose_name=' Film ')),
                ('grade', models.IntegerField(verbose_name=' Grade ')),
                ('color', models.IntegerField(verbose_name=' Neg or Pos ')),
            ],
        ),
    ]
