# Generated by Django 3.0.8 on 2022-04-03 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='color',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='name',
        ),
    ]
